### PR TITLE
Upgrade xxhash to use Nan>=2.0, add unit test

### PR DESCRIPTION
**Pull request by chaosgame**
Upgrading to Nan 2.0 is required for running xxhash with io.js 3.x and higher.

### CODE REVIEW

**Comment by chaosgame** [comment]
Addresses https://github.com/mscdex/node-xxhash/issues/9.

**Comment by asilvas** [comment]
+1 bump

**Comment by ChALkeR** [comment]
Adding to the list: https://github.com/nodejs/node/issues/2798.

**Comment by mscdex** [comment]
Landed in c5fb41eb4f. Thanks!

**Pull request closed without merging**
